In [1]:
import random
import numpy as np

### Generate multiplication table
to do that, we set the max number n for the multiplication table, then we will generate a matrix with nxn numbers.
$$f(i,j) = i * j$$
$\frac{dy}{dt}=2t^2$
In equation \eqref{eq:sample}, we find the value of an
interesting integral:

\begin{equation}
  \int_0^\infty \frac{x^3}{e^x-1}\,dx = \frac{\pi^4}{15}
  \label{eq:sample}
\end{equation}

In [4]:
max_number=50
rows_count=10
def multi_table():
    row=np.arange(1,max_number + 1)
    col=np.arange(1,max_number + 1)

    ret_rows=[]
    for r in row:
        ret_row = []
        for c in col:
            ret = r*c
            ret_row.append(r*c)
        ret_rows.append(ret_row)
    table = np.vstack(ret_rows)
    return table
def generate_multi(cols):
    rows=[]
    for i in range(1,rows_count + 1):
        row=[]
        for i in range(cols):
            a,b=random.randint(1,max_number), random.randint(1,max_number)
            row.append("{} x {} = {}".format(a,b,a*b))
        rows.append(row)
    return rows
def generate_divide(table, cols):
    rows = []
    for x in range(1, rows_count + 1):
        row = []
        for i in range(cols):
            r=random.randint(0,max_number - 1)
            c=random.randint(0,max_number - 1)
            row.append("{} / {} = {}".format(table[r][c], r+1,c+1))
        rows.append(row)
    return rows

In [5]:
table = multi_table()
print(table)
for r in generate_multi(4):
    print("{:<25}{:<25}{:<25}{}".format(*r))
print("\r\n")
for r in generate_divide(table, 4):
    print("{:<25}{:<25}{:<25}{}".format(*r))

[[   1    2    3 ...   48   49   50]
 [   2    4    6 ...   96   98  100]
 [   3    6    9 ...  144  147  150]
 ...
 [  48   96  144 ... 2304 2352 2400]
 [  49   98  147 ... 2352 2401 2450]
 [  50  100  150 ... 2400 2450 2500]]
34 x 37 = 1258           10 x 19 = 190            11 x 5 = 55              38 x 8 = 304
13 x 12 = 156            1 x 26 = 26              6 x 32 = 192             21 x 43 = 903
7 x 37 = 259             37 x 2 = 74              24 x 3 = 72              13 x 14 = 182
18 x 24 = 432            50 x 21 = 1050           12 x 22 = 264            13 x 17 = 221
47 x 5 = 235             36 x 3 = 108             16 x 7 = 112             28 x 17 = 476
23 x 33 = 759            48 x 4 = 192             24 x 35 = 840            21 x 13 = 273
5 x 41 = 205             20 x 1 = 20              23 x 27 = 621            31 x 50 = 1550
34 x 47 = 1598           9 x 28 = 252             43 x 2 = 86              12 x 20 = 240
24 x 2 = 48              32 x 9 = 288             11 x 41 = 